apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iv85fotsu-nodejs 
  janus-idp.io/tekton: iv85fotsu-nodejs
  backstage.io/kubernetes-id: iv85fotsu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iv85fotsu-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml